%General Mission Analysis Tool(GMAT) Script
%Created: 2025-05-21 23:15:53


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft Chaser;
GMAT Chaser.DateFormat = TAIModJulian;
GMAT Chaser.Epoch = '21545';
GMAT Chaser.CoordinateSystem = EarthFixed;
GMAT Chaser.DisplayStateType = Cartesian;
GMAT Chaser.X = 6378.099999999998;
GMAT Chaser.Y = 4.871362051939035e-13;
GMAT Chaser.Z = -1.745825706223059e-13;
GMAT Chaser.VX = 7.587536432073239e-16;
GMAT Chaser.VY = 7.800000000000001;
GMAT Chaser.VZ = 4.113128464395838e-17;
GMAT Chaser.DryMass = 450;
GMAT Chaser.Cd = 2.2;
GMAT Chaser.Cr = 1.8;
GMAT Chaser.DragArea = 15;
GMAT Chaser.SRPArea = 1;
GMAT Chaser.SPADDragScaleFactor = 1;
GMAT Chaser.SPADSRPScaleFactor = 1;
GMAT Chaser.AtmosDensityScaleFactor = 1;
GMAT Chaser.ExtendedMassPropertiesModel = 'None';
GMAT Chaser.NAIFId = -10003001;
GMAT Chaser.NAIFIdReferenceFrame = -9003001;
GMAT Chaser.OrbitColor = Red;
GMAT Chaser.TargetColor = Teal;
GMAT Chaser.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT Chaser.CdSigma = 1e+70;
GMAT Chaser.CrSigma = 1e+70;
GMAT Chaser.Id = 'SatId';
GMAT Chaser.Attitude = CoordinateSystemFixed;
GMAT Chaser.SPADSRPInterpolationMethod = Bilinear;
GMAT Chaser.SPADSRPScaleFactorSigma = 1e+70;
GMAT Chaser.SPADDragInterpolationMethod = Bilinear;
GMAT Chaser.SPADDragScaleFactorSigma = 1e+70;
GMAT Chaser.AtmosDensityScaleFactorSigma = 1e+70;
GMAT Chaser.ModelFile = 'aura.3ds';
GMAT Chaser.ModelOffsetX = 0;
GMAT Chaser.ModelOffsetY = 0;
GMAT Chaser.ModelOffsetZ = 0;
GMAT Chaser.ModelRotationX = 0;
GMAT Chaser.ModelRotationY = 0;
GMAT Chaser.ModelRotationZ = 0;
GMAT Chaser.ModelScale = 1;
GMAT Chaser.AttitudeDisplayStateType = 'Quaternion';
GMAT Chaser.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT Chaser.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT Chaser.EulerAngleSequence = '321';

Create Spacecraft TargetSat;
GMAT TargetSat.DateFormat = TAIModJulian;
GMAT TargetSat.Epoch = '21545';
GMAT TargetSat.CoordinateSystem = EarthFixed;
GMAT TargetSat.DisplayStateType = Cartesian;
GMAT TargetSat.X = 5984.999999999997;
GMAT TargetSat.Y = 2172.000000000001;
GMAT TargetSat.Z = 2184.999999999999;
GMAT TargetSat.VX = 6.938893903907228e-16;
GMAT TargetSat.VY = 7.7;
GMAT TargetSat.VZ = 4.482424241486873e-17;
GMAT TargetSat.DryMass = 350;
GMAT TargetSat.Cd = 2.2;
GMAT TargetSat.Cr = 1.8;
GMAT TargetSat.DragArea = 15;
GMAT TargetSat.SRPArea = 1;
GMAT TargetSat.SPADDragScaleFactor = 1;
GMAT TargetSat.SPADSRPScaleFactor = 1;
GMAT TargetSat.AtmosDensityScaleFactor = 1;
GMAT TargetSat.ExtendedMassPropertiesModel = 'None';
GMAT TargetSat.NAIFId = -10004001;
GMAT TargetSat.NAIFIdReferenceFrame = -9004001;
GMAT TargetSat.OrbitColor = Green;
GMAT TargetSat.TargetColor = LightGray;
GMAT TargetSat.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT TargetSat.CdSigma = 1e+70;
GMAT TargetSat.CrSigma = 1e+70;
GMAT TargetSat.Id = 'SatId';
GMAT TargetSat.Attitude = CoordinateSystemFixed;
GMAT TargetSat.SPADSRPInterpolationMethod = Bilinear;
GMAT TargetSat.SPADSRPScaleFactorSigma = 1e+70;
GMAT TargetSat.SPADDragInterpolationMethod = Bilinear;
GMAT TargetSat.SPADDragScaleFactorSigma = 1e+70;
GMAT TargetSat.AtmosDensityScaleFactorSigma = 1e+70;
GMAT TargetSat.ModelFile = 'aura.3ds';
GMAT TargetSat.ModelOffsetX = 0;
GMAT TargetSat.ModelOffsetY = 0;
GMAT TargetSat.ModelOffsetZ = 0;
GMAT TargetSat.ModelRotationX = 0;
GMAT TargetSat.ModelRotationY = 0;
GMAT TargetSat.ModelRotationZ = 0;
GMAT TargetSat.ModelScale = 1;
GMAT TargetSat.AttitudeDisplayStateType = 'Quaternion';
GMAT TargetSat.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT TargetSat.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT TargetSat.EulerAngleSequence = '321';



%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
GMAT DefaultProp_ForceModel.CentralBody = Earth;
GMAT DefaultProp_ForceModel.PrimaryBodies = {Earth};
GMAT DefaultProp_ForceModel.Drag = None;
GMAT DefaultProp_ForceModel.SRP = Off;
GMAT DefaultProp_ForceModel.RelativisticCorrection = Off;
GMAT DefaultProp_ForceModel.ErrorControl = RSSStep;
GMAT DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.Order = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
GMAT DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
GMAT DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
GMAT DefaultProp.Type = RungeKutta4;
GMAT DefaultProp.InitialStepSize = 60;
GMAT DefaultProp.Accuracy = 9.999999999999999e-12;
GMAT DefaultProp.MinStep = 0.001;
GMAT DefaultProp.MaxStep = 2700;
GMAT DefaultProp.MaxStepAttempts = 50;
GMAT DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Burns
%----------------------------------------

Create ImpulsiveBurn ImpulsiveBurn1;
GMAT ImpulsiveBurn1.CoordinateSystem = Local;
GMAT ImpulsiveBurn1.Origin = Earth;
GMAT ImpulsiveBurn1.Axes = VNB;
GMAT ImpulsiveBurn1.Element1 = 0.5;
GMAT ImpulsiveBurn1.Element2 = 0.8;
GMAT ImpulsiveBurn1.Element3 = 0.5;
GMAT ImpulsiveBurn1.DecrementMass = false;
GMAT ImpulsiveBurn1.Isp = 300;
GMAT ImpulsiveBurn1.GravitationalAccel = 9.81;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
GMAT DefaultOrbitView.SolverIterations = Current;
GMAT DefaultOrbitView.UpperLeft = [ 0.001176470588235294 0 ];
GMAT DefaultOrbitView.Size = [ 0.5 0.5171102661596958 ];
GMAT DefaultOrbitView.RelativeZOrder = 324;
GMAT DefaultOrbitView.Maximized = true;
GMAT DefaultOrbitView.Add = {Chaser, TargetSat, Earth};
GMAT DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.DrawObject = [ true true true ];
GMAT DefaultOrbitView.DataCollectFrequency = 1;
GMAT DefaultOrbitView.UpdatePlotFrequency = 50;
GMAT DefaultOrbitView.NumPointsToRedraw = 0;
GMAT DefaultOrbitView.ShowPlot = true;
GMAT DefaultOrbitView.MaxPlotPoints = 20000;
GMAT DefaultOrbitView.ShowLabels = true;
GMAT DefaultOrbitView.ViewPointReference = Chaser;
GMAT DefaultOrbitView.ViewPointVector = [ 30000 0 0 ];
GMAT DefaultOrbitView.ViewDirection = TargetSat;
GMAT DefaultOrbitView.ViewScaleFactor = 1;
GMAT DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.ViewUpAxis = Z;
GMAT DefaultOrbitView.EclipticPlane = Off;
GMAT DefaultOrbitView.XYPlane = On;
GMAT DefaultOrbitView.WireFrame = Off;
GMAT DefaultOrbitView.Axes = On;
GMAT DefaultOrbitView.Grid = Off;
GMAT DefaultOrbitView.SunLine = Off;
GMAT DefaultOrbitView.UseInitialView = Off;
GMAT DefaultOrbitView.StarCount = 7000;
GMAT DefaultOrbitView.EnableStars = On;
GMAT DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
GMAT DefaultGroundTrackPlot.SolverIterations = Current;
GMAT DefaultGroundTrackPlot.UpperLeft = [ 0.000588235294117647 0.5171102661596958 ];
GMAT DefaultGroundTrackPlot.Size = [ 0.4994117647058823 0.5158428390367554 ];
GMAT DefaultGroundTrackPlot.RelativeZOrder = 322;
GMAT DefaultGroundTrackPlot.Maximized = true;
GMAT DefaultGroundTrackPlot.Add = {Chaser, TargetSat};
GMAT DefaultGroundTrackPlot.DataCollectFrequency = 1;
GMAT DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
GMAT DefaultGroundTrackPlot.NumPointsToRedraw = 0;
GMAT DefaultGroundTrackPlot.ShowPlot = true;
GMAT DefaultGroundTrackPlot.MaxPlotPoints = 20000;
GMAT DefaultGroundTrackPlot.CentralBody = Earth;
GMAT DefaultGroundTrackPlot.TextureMap = 'ModifiedBlueMarble.jpg';


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate DefaultProp(Chaser, TargetSat) {Chaser.ElapsedSecs = 50};
Maneuver ImpulsiveBurn1(Chaser);
Propagate DefaultProp(Chaser, TargetSat) {Chaser.ElapsedSecs = 1158, TargetSat.ElapsedSecs = 1158};
